troll-bot:
  restart: always
  image: pando85/troll-bot
  links:
    - mongo
  ports:
     - "5000:5000"
  volumes:
    - ./cert.pem:/tmp/cert.pem:ro
  environment:
    - BOT_TOKEN= Telegram Bot API token
    - BOT_URL= Telegram Bot URL
    - CERTIFICATE_PATH=/tmp/cert.pem
    - DB_HOST=mongo
    - DB_PORT=27017

mongo:
  restart: always
  image: mongo
  volumes_from:
    - data
  expose:
    - "27017"

data:
  restart: always  
  image: mongo:3.2.4
  volumes:
    - /data/db
  command: "true"
  