service:
  restart: always
  build: ./service
  links:
    - mongo
  ports:
     - "5000:5000"
  environment:
    - BOT_TOKEN= Telegram API token
    - BOT_URL=https://telegram-bot.mooo.com
    - CERTIFICATE_PATH=cert.pem
    - DB_HOST=mongo
    - DB_PORT=27017

mongo:
  restart: always
  image: mongo
  volumes_from:
    - data
  expose:
    - "27017"

data:
  restart: always  
  image: mongo:3.2.4
  volumes:
    - /data/db
  command: --break-mongo
